package bgu.spl.net.api;
import bgu.spl.net.srv.ConnectionHandler;
import bgu.spl.net.srv.ConnectionsImpl;

public class StompTester {

    public static void main(String[] args) {
        // 1. Initialize real implementations
        ConnectionsImpl<String> connections = new ConnectionsImpl<>();
        StompProtocolImpl protocol = new StompProtocolImpl();
        int connectionId = 123;

        // 2. Create a handler that prints the final STOMP frames generated by ConnectionsImpl
        ConnectionHandler<String> handler = new ConnectionHandler<String>() {
            @Override
            public void send(String msg) {
                // This prints the actual frame sent over the "network"
                System.out.println("<<< [FRAME TO CLIENT]:\n" + msg);
            }
            @Override
            public void close() {}
        };

        // 3. Register the handler in your real ConnectionsImpl map
        connections.addClientToActiveClients(connectionId, handler);
        
        // 4. Start the protocol instance
        protocol.start(connectionId, connections);

        System.out.println("--- Starting STOMP Integration Test ---");

        // TEST 1: CONNECT
        // Note: This will call your Database.java; ensure it handles these credentials.
        process(protocol, "CONNECT\n" +
                "accept-version:1.2\n" +
                "host:stomp.cs.bgu.ac.il\n" +
                "login:meni\n" +
                "passcode:films\n");

        
        process(protocol, "SUBSCRIBE\n" +
                "destination:/topic/world_cup\n" +
                "id:5\n" +
                "receipt:71\n");
        process(protocol, "SUBSCRIBE\n" +
                "destination:/topic/world_cup\n" +
                "id:4\n" +
                "receipt:15\n");
        // TEST 2: SUBSCRIBE
        // Triggers addClientToTopic in ConnectionsImpl.
        process(protocol, "SUBSCRIBE\n" +
                "destination:/topic/world_cup\n" +
                "id:17\n" +
                "receipt:73\n");

        // TEST 3: SEND (Multi-line body)
        // Tests your parsing and the message distribution in ConnectionsImpl.
        process(protocol, "SEND\n" +
                "destination:/topic/world_cup\n" +
                "\n" +
                "GOAL!\n" +
                "Argentina scores!\n" +
                "Final score: 1-0.\n");

        // TEST 4: DISCONNECT
        process(protocol, "DISCONNECT\n" +
                "receipt:82\n");
    }

    private static void process(StompProtocolImpl protocol, String frame) {
        System.out.println("\n>>> SENDING FRAME TO PROTOCOL:\n" + frame.replace("\u0000", "[NULL]"));
        try {
            protocol.process(frame);
        } catch (Exception e) {
            System.out.println("[ERROR] Exception during process: " + e.getMessage());
            e.printStackTrace();
        }
    }
}